### ISSUE TITLE
Feature suggestion: Specify which branches to push to

### ISSUE THREAD

**Issue by Alexejhero** [kbrashears5/github-action-file-sync#1]
Currently, when the file is updated, the changes are only pushed to the master branch. It would be helpful to have a configurable option for the branches on which you want the files to be automatically updated, or even select all of them.

**Comment by kbrashears5** [comment]
v2.0.0 supports this now. It will use the origin branch if it exists, if not, then it will create it.

See the [README](https://github.com/kbrashears5/github-action-file-sync) for full details
