### ISSUE TITLE
sync file in a specific folder

### ISSUE THREAD

**Issue by sunn-e** [kbrashears5/github-action-file-sync#2]
Is it possible to sync file in a specific folder?

**Comment by sunn-e** [comment]
I want to copy all files from source folder to a destination folder. Is it possible to do so?
I tried putting /* at folder end to get all files. I also tried to specify a custom folder with respect to root as "`/dest_folder` but it did not work. It wrote the files to root folder instead. Let me know.
Update:
It turns out,using `source_path/*` , it considers wildcard symbol as a file name and since there is no `*` file in `source_path` folder, it doesn't work as expected. Still looking for a solution. :/

**Comment by sunn-e** [comment]
> 
> 
> Is it possible to sync file in a specific folder?

This is solved. It turns out you need not put extra space around `=` sign .  Like `source_path=dest_path` rather than `source_path = dest_path`

**Comment by kbrashears5** [comment]
@sunn-e yea, I hadn't thought about that, syncing a folder, but turns out the bash `cp` command can do either files or folders so it's just a matter of getting the path right.

I'll get a fix in for `source_path=dest_path` vs `source_path = dest_path`

**Comment by kbrashears5** [comment]
@sunn-e turns out I can't do the trimming, see the [troubleshooting](https://github.com/kbrashears5/github-action-file-sync/blob/master/README.md) section for details why.

I'm curious how you got the folder sync working, could you share details?

**Comment by kbrashears5** [comment]
@sunn-e nevermind, was able to figure out the folder sync

v2.2.0 has some fixes if you'd like to upgrade

**Comment by sunn-e** [comment]
> It turns out,using `source_path/*` , it considers wildcard symbol as a file name and since there is no `*` file in `source_path` folder, it doesn't work as expected. Still looking for a solution. :/

Do you think this can work out, like `cp -R <source_folder>/* <destination_folder>` so that we can only copy files in a source folder to choice of destination folder.

**Comment by kbrashears5** [comment]
This will copy entire contents of `sourceFolder` to the folder called `destinationFolder` (note the slashes):
```yaml
FILES: |
    sourceFolder/=destinationFolder/
```
