### ISSUE TITLE
How to copy content of a directory to root directory of destination repo

### ISSUE THREAD

**Issue by slawekjaranowski** [kbrashears5/github-action-file-sync#5]
I want to copy content of some directory to root directory of destination repo,

I tryed many options .... with out result
like:

```
            common-files/=.

            common-files/=./

```

you can see history of repo: https://github.com/s4u/.github/commits/master

**Comment by slawekjaranowski** [comment]
I have solution, definition like:
```
          FILES: |
            common-files/.
```

causes to copy content of  common-files/. to root directory of destination repo.

**Comment by kbrashears5** [comment]
I have examples in the [README](https://github.com/kbrashears5/github-action-file-sync/blob/master/README.md)

Yours would look like:
```yaml
FILES: |
    common-files/
```
